import {
  BadRequestException,
  Injectable,
  NotFoundException
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { UsersService } from '../users/users.service';
import { Memo, MemoStatus, Visibility } from './entity/memo.entity';

type CreateMemoParams = {
  title?: string;
  body: string;
  visibility: Visibility;
  latitude: number;
  longitude: number;
  placeName?: string;
  triggerRadius?: number;
  expiresAt?: string;
};

type UpdateMemoParams = Partial<CreateMemoParams>;

type FindMyMemosParams = {
  tab?: string;
  sort?: string;
  latitude?: number;
  longitude?: number;
};

type FindNearbyPublicMemosParams = {
  latitude: number;
  longitude: number;
  radius?: number;
};

const ALLOWED_TRIGGER_RADII = [50, 100, 200, 500] as const;
const DEFAULT_TRIGGER_RADIUS = 100;
const DEFAULT_PUBLIC_EXPIRATION_DAYS = 30;
const DEFAULT_PUBLIC_EXPLORE_RADIUS = 500;

@Injectable()
export class MemosService {
  constructor(
    @InjectRepository(Memo)
    private readonly memosRepository: Repository<Memo>,
    private readonly usersService: UsersService
  ) {}

  async findAllByUser(userId: string, params: FindMyMemosParams) {
    await this.validateUserOrThrow(userId);

    const memos = await this.memosRepository.find({
      where: { user: { id: userId } },
      relations: { user: true },
      order: { createdAt: 'DESC' }
    });

    const syncedMemos = await this.syncExpiredStatuses(memos);
    const filteredMemos = this.filterMyMemosByTab(syncedMemos, params.tab);
    const sortedMemos = this.sortMemos(filteredMemos, params);

    return sortedMemos.map((memo) => this.toMemoResponse(memo, params));
  }

  async findOneByUser(userId: string, memoId: string) {
    const memo = await this.findOwnedMemoEntity(userId, memoId);
    const [syncedMemo] = await this.syncExpiredStatuses([memo]);
    return this.toMemoResponse(syncedMemo);
  }

  async create(userId: string, params: CreateMemoParams) {
    const user = await this.validateUserOrThrow(userId);
    const normalized = this.normalizeCreateParams(params);

    const memo = this.memosRepository.create({
      user,
      ...normalized
    });

    const savedMemo = await this.memosRepository.save(memo);
    return this.toMemoResponse(savedMemo);
  }

  async update(userId: string, memoId: string, params: UpdateMemoParams) {
    const memo = await this.findOwnedMemoEntity(userId, memoId);

    if (memo.status === MemoStatus.EXPIRED) {
      throw new BadRequestException('만료된 메모는 수정할 수 없습니다.');
    }

    const previousBody = memo.body;

    if (params.visibility !== undefined) {
      this.validateVisibility(params.visibility);
      memo.visibility = params.visibility;
    }

    if (params.body !== undefined) {
      memo.body = this.validateBody(params.body);
    }

    if (params.title !== undefined) {
      memo.title = this.normalizeTitle(params.title, memo.body);
    } else if (
      params.body !== undefined &&
      this.isAutoGeneratedTitle(memo.title, previousBody)
    ) {
      memo.title = this.normalizeTitle(undefined, memo.body);
    }

    if (params.placeName !== undefined) {
      memo.placeName = this.normalizePlaceName(params.placeName);
    }

    if (params.latitude !== undefined) {
      memo.latitude = this.validateLatitude(params.latitude);
    }

    if (params.longitude !== undefined) {
      memo.longitude = this.validateLongitude(params.longitude);
    }

    if (params.triggerRadius !== undefined) {
      memo.triggerRadius = this.validateTriggerRadius(params.triggerRadius);
    }

    if (memo.visibility === Visibility.PUBLIC) {
      if (params.expiresAt !== undefined) {
        memo.expiresAt = this.parseExpiration(params.expiresAt);
      } else if (!memo.expiresAt) {
        memo.expiresAt = this.createDefaultPublicExpiration();
      }
    } else {
      memo.expiresAt = null;
      memo.status = MemoStatus.ACTIVE;
    }

    memo.status = this.computeStatus(memo);

    const savedMemo = await this.memosRepository.save(memo);
    return this.toMemoResponse(savedMemo);
  }

  async remove(userId: string, memoId: string) {
    const memo = await this.findOwnedMemoEntity(userId, memoId);
    await this.memosRepository.remove(memo);

    return { id: memoId, deleted: true };
  }

  async findNearbyPublicMemos(params: FindNearbyPublicMemosParams) {
    const latitude = this.validateLatitude(params.latitude);
    const longitude = this.validateLongitude(params.longitude);
    const radius = params.radius ?? DEFAULT_PUBLIC_EXPLORE_RADIUS;

    if (radius <= 0) {
      throw new BadRequestException('Radius must be greater than 0.');
    }

    const memos = await this.memosRepository.find({
      where: {
        visibility: Visibility.PUBLIC,
        status: MemoStatus.ACTIVE
      },
      relations: { user: true }
    });

    const syncedMemos = await this.syncExpiredStatuses(memos);

    return syncedMemos
      .filter((memo) => memo.visibility === Visibility.PUBLIC)
      .map((memo) => ({
        memo,
        distanceMeters: this.calculateDistanceMeters(
          latitude,
          longitude,
          Number(memo.latitude),
          Number(memo.longitude)
        )
      }))
      .filter(({ memo, distanceMeters }) => {
        const isActive = memo.status === MemoStatus.ACTIVE;
        return isActive && distanceMeters <= radius;
      })
      .sort((a, b) => a.distanceMeters - b.distanceMeters)
      .map(({ memo, distanceMeters }) =>
        this.toMemoResponse(memo, { latitude, longitude, radius }, distanceMeters)
      );
  }

  private async validateUserOrThrow(userId: string) {
    const user = await this.usersService.findById(userId);

    if (!user) {
      throw new NotFoundException('User not found.');
    }

    return user;
  }

  private async findOwnedMemoEntity(userId: string, memoId: string) {
    await this.validateUserOrThrow(userId);

    const memo = await this.memosRepository.findOne({
      where: { id: memoId, user: { id: userId } },
      relations: { user: true }
    });

    if (!memo) {
      throw new NotFoundException('Memo not found.');
    }

    return memo;
  }

  private validateVisibility(value: Visibility) {
    if (!Object.values(Visibility).includes(value)) {
      throw new BadRequestException('Invalid visibility value.');
    }
  }

  private normalizeCreateParams(params: CreateMemoParams) {
    this.validateVisibility(params.visibility);

    const body = this.validateBody(params.body);
    const title = this.normalizeTitle(params.title, body);
    const latitude = this.validateLatitude(params.latitude);
    const longitude = this.validateLongitude(params.longitude);
    const triggerRadius = this.validateTriggerRadius(params.triggerRadius);
    const placeName = this.normalizePlaceName(params.placeName);
    const expiresAt =
      params.visibility === Visibility.PUBLIC
        ? this.parseExpiration(params.expiresAt) ?? this.createDefaultPublicExpiration()
        : null;

    return {
      title,
      body,
      visibility: params.visibility,
      latitude,
      longitude,
      placeName,
      triggerRadius,
      expiresAt,
      status: MemoStatus.ACTIVE as MemoStatus
    };
  }

  private validateBody(body: string) {
    const normalized = body?.trim();

    if (!normalized || normalized.length < 1 || normalized.length > 1000) {
      throw new BadRequestException('Body must be between 1 and 1000 characters.');
    }

    return normalized;
  }

  private normalizeTitle(title: string | undefined, body: string) {
    const normalizedTitle = title?.trim();

    if (normalizedTitle) {
      return normalizedTitle.slice(0, 100);
    }

    return body.slice(0, 10);
  }

  private isAutoGeneratedTitle(title: string, body: string) {
    return title === body.slice(0, 10);
  }

  private normalizePlaceName(placeName: string | undefined) {
    const normalized = placeName?.trim();
    return normalized ? normalized.slice(0, 255) : null;
  }

  private validateLatitude(latitude: number) {
    if (!Number.isFinite(latitude) || latitude < -90 || latitude > 90) {
      throw new BadRequestException('Latitude must be between -90 and 90.');
    }

    return latitude;
  }

  private validateLongitude(longitude: number) {
    if (!Number.isFinite(longitude) || longitude < -180 || longitude > 180) {
      throw new BadRequestException('Longitude must be between -180 and 180.');
    }

    return longitude;
  }

  private validateTriggerRadius(radius?: number) {
    const normalized = radius ?? DEFAULT_TRIGGER_RADIUS;

    if (!ALLOWED_TRIGGER_RADII.includes(normalized as (typeof ALLOWED_TRIGGER_RADII)[number])) {
      throw new BadRequestException('Trigger radius must be one of 50, 100, 200, 500.');
    }

    return normalized;
  }

  private parseExpiration(value?: string) {
    if (!value) {
      return null;
    }

    const expiresAt = new Date(value);

    if (Number.isNaN(expiresAt.getTime())) {
      throw new BadRequestException('expiresAt must be a valid ISO datetime string.');
    }
 
    return expiresAt;
  }

  private createDefaultPublicExpiration() {
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + DEFAULT_PUBLIC_EXPIRATION_DAYS);
    return expiresAt;
  }

  private computeStatus(memo: Memo) {
    if (memo.visibility === Visibility.PUBLIC && memo.expiresAt) {
      return memo.expiresAt.getTime() <= Date.now()
        ? MemoStatus.EXPIRED
        : MemoStatus.ACTIVE;
    }

    return MemoStatus.ACTIVE;
  }

  private async syncExpiredStatuses(memos: Memo[]) {
    const changedMemos: Memo[] = [];

    for (const memo of memos) {
      const nextStatus = this.computeStatus(memo);
      if (memo.status !== nextStatus) {
        memo.status = nextStatus;
        changedMemos.push(memo);
      }
    }

    if (changedMemos.length > 0) {
      await this.memosRepository.save(changedMemos);
    }

    return memos;
  }

  private filterMyMemosByTab(memos: Memo[], tab?: string) {
    switch (tab) {
      case 'private':
        return memos.filter((memo) => memo.visibility === Visibility.PRIVATE);
      case 'public':
        return memos.filter(
          (memo) =>
            memo.visibility === Visibility.PUBLIC &&
            memo.status !== MemoStatus.EXPIRED
        );
      case 'expired':
        return memos.filter((memo) => memo.status === MemoStatus.EXPIRED);
      default:
        return memos;
    }
  }

  private sortMemos(memos: Memo[], params: FindMyMemosParams) {
    const sorted = [...memos];

    switch (params.sort) {
      case 'expiresSoon':
        return sorted.sort((a, b) => {
          const aTime = a.expiresAt?.getTime() ?? Number.MAX_SAFE_INTEGER;
          const bTime = b.expiresAt?.getTime() ?? Number.MAX_SAFE_INTEGER;
          return aTime - bTime;
        });
      case 'distance':
        if (params.latitude === undefined || params.longitude === undefined) {
          throw new BadRequestException(
            'latitude and longitude are required for distance sorting.'
          );
        }

        return sorted.sort((a, b) => {
          const aDistance = this.calculateDistanceMeters(
            params.latitude!,
            params.longitude!,
            Number(a.latitude),
            Number(a.longitude)
          );
          const bDistance = this.calculateDistanceMeters(
            params.latitude!,
            params.longitude!,
            Number(b.latitude),
            Number(b.longitude)
          );

          return aDistance - bDistance;
        });
      case 'recent':
      default:
        return sorted.sort(
          (a, b) => b.createdAt.getTime() - a.createdAt.getTime()
        );
    }
  }

  private calculateDistanceMeters(
    originLat: number,
    originLng: number,
    targetLat: number,
    targetLng: number
  ) {
    const toRadians = (value: number) => (value * Math.PI) / 180;
    const earthRadiusMeters = 6371000;
    const latDelta = toRadians(targetLat - originLat);
    const lngDelta = toRadians(targetLng - originLng);
    const startLat = toRadians(originLat);
    const endLat = toRadians(targetLat);

    const a =
      Math.sin(latDelta / 2) ** 2 +
      Math.cos(startLat) * Math.cos(endLat) * Math.sin(lngDelta / 2) ** 2;

    return 2 * earthRadiusMeters * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  }

  // 기능명세서 6-3: 만료된 공개 메모 재공개 (내부적으로 새 메모 생성)
  async republish(userId: string, memoId: string, expiresAt?: string) {
    const memo = await this.findOwnedMemoEntity(userId, memoId);
    await this.syncExpiredStatuses([memo]);

    if (memo.status !== MemoStatus.EXPIRED) {
      throw new BadRequestException('만료된 메모만 재공개할 수 있습니다.');
    }

    if (memo.visibility !== Visibility.PUBLIC) {
      throw new BadRequestException('공개 메모만 재공개할 수 있습니다.');
    }

    const newExpiresAt = this.parseExpiration(expiresAt) ?? this.createDefaultPublicExpiration();

    const newMemo = this.memosRepository.create({
      user: memo.user,
      visibility: Visibility.PUBLIC,
      title: memo.title,
      body: memo.body,
      placeName: memo.placeName,
      latitude: memo.latitude,
      longitude: memo.longitude,
      triggerRadius: memo.triggerRadius,
      status: MemoStatus.ACTIVE,
      expiresAt: newExpiresAt
    });

    const saved = await this.memosRepository.save(newMemo);
    return this.toMemoResponse(saved);
  }

  private toMemoResponse(
    memo: Memo,
    context?: { latitude?: number; longitude?: number; radius?: number },
    distanceMeters?: number
  ) {
    const computedDistance =
      distanceMeters !== undefined
        ? distanceMeters
        : context?.latitude !== undefined && context.longitude !== undefined
          ? this.calculateDistanceMeters(
              context.latitude,
              context.longitude,
              Number(memo.latitude),
              Number(memo.longitude)
            )
          : undefined;

    return {
      id: memo.id,
      title: memo.title,
      body: memo.body,
      visibility: memo.visibility,
      status: memo.status,
      placeName: memo.placeName,
      latitude: Number(memo.latitude),
      longitude: Number(memo.longitude),
      triggerRadius: memo.triggerRadius,
      expiresAt: memo.expiresAt,
      createdAt: memo.createdAt,
      updatedAt: memo.updatedAt,
      authorId: memo.user?.id,
      distanceMeters:
        computedDistance !== undefined ? Math.round(computedDistance) : undefined
    };
  }
}
